name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: version string (eg. 6.1)
        required: true

jobs:
  create-release:
    name: Version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    env:
      ADDON_NAME: Review Hotmouse
      # Path of files to put inside addon root when creating addon file. Whitespace separated.
      BUNDLE_FILES: LICENSE README.md
      # Path of addon root in repo.
      ADDON_ROOT: addon
      ADDON_FILE_NAME: review_hotmouse_v${{ github.event.inputs.version }}.ankiaddon

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python -m pip install simplejson

      - name: Run new_version.py
        run: python new_version.py ${{ github.event.inputs.version }} ${{ env.ADDON_ROOT }}

      - name: Commit and push changes to git
        uses: EndBug/add-and-commit@v7.1.1
        with:
          message: Bump version to v${{ github.event.inputs.version }}

      - name: Bundle files into addon root
        run: cp ${{ env.BUNDLE_FILES }} ${{ env.ADDON_ROOT }}

      - name: Create ankiaddon file
        run: |
          base_path="$PWD"
          cd "${{ env.ADDON_ROOT }}"
          zip -r "$base_path/${{ env.ADDON_FILE_NAME }}" *
          cd "$base_path"

      - name: Create github release and upload ankiaddon file
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.ADDON_FILE_NAME }}
          tag: ${{ github.event.inputs.version }}
          release_name: ${{ env.ADDON_NAME }} v${{ github.event.inputs.version }}
